"""Build RECIPES.md from the recipe files in recipes/."""

from pathlib import Path

RECIPES_DIR = Path("recipes")
OUTPUT_FILE = Path("RECIPES.md")
CATEGORIES = ["breakfast", "main", "dessert", "drinks"]


def read_front_matter(path):
    """Return the front matter fields of a recipe as a dict."""
    lines = path.read_text(encoding="utf-8").splitlines()
    fields = {}
    if not lines or lines[0].strip() != "---":
        return fields
    for line in lines[1:]:
        if line.strip() == "---":
            break
        key, _, value = line.partition(":")
        fields[key.strip()] = value.split("#")[0].strip()
    return fields


def collect_recipes():
    """Group recipes by category."""
    recipes = {category: [] for category in CATEGORIES}
    for path in sorted(RECIPES_DIR.rglob("*.md")):
        fields = read_front_matter(path)
        category = fields.get("category")
        if category in recipes:
            recipes[category].append((fields["name"], path))
    return recipes


def build_index(recipes):
    """Return the content of RECIPES.md."""
    lines = [
        "# Recipes",
        "",
        "This file is generated by `scripts/build_index.py`. Don't edit it by hand.",
        "",
    ]
    for category in CATEGORIES:
        lines.append(f"## {category.capitalize()}")
        lines.append("")
        if not recipes[category]:
            lines.append("_No recipes yet._")
        for name, path in recipes[category]:
            lines.append(f"- [{name}]({path.as_posix()})")
        lines.append("")
    return "\n".join(lines)


def main():
    recipes = collect_recipes()
    OUTPUT_FILE.write_text(build_index(recipes), encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
